# This is a basic workflow that is manually triggered

name: CI-IB trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

# Trigger the workflow on a pull request event merge - only for the main branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# Workflow will execute CMake to build x64 Release then call Incredibuild to distribute compilation.
jobs:
    build:
      # The type of runner that the job will run on
      runs-on: self-hosted
      defaults:
        run:
           shell: powershell

    # Steps/tasks to execute
      steps:
      - uses: actions/checkout@v2

      - name: cmake x64 release
        run: |
            cd C:\thelab\code\github\ib-opencv-demo\out\build
            write-output "Updating Path"
            $env:Path += ";C:\Program Files\Cmake\bin;C:\Program Files (x86)\Incredibuild"
            write-output "Updated Path"
            write-output "Executing cmake..."
            cmake -G "Visual Studio 16 2019" -A x64 -S ..\.. -B "x64-Release"
    
    incredibuild:
      # Type of runner job will run on
      runs-on: self-hosted
      defaults:
        run:
           shell: powershell

      # We need the build job completed to compile
      needs: build

      # Steps/tasks to execute
      steps:
      - uses: actions/checkout@v2

      - name: have Incredibuild run and distribute the compilation to the grid
        run: |
            cd C:\thelab\code\github\ib-opencv-demo\out\build\x64-Release
            write-output "Updating Path"
            $env:Path += ";C:\Program Files\Cmake\bin;C:\Program Files (x86)\Incredibuild"
            write-output "Updated Path"
            write-output "Executing Incredibuild..."
            BuildConsole OpenCV.sln /rebuild /cfg="Release|x64"

