# This is a basic workflow that is manually triggered

name: CI-IB trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

# Trigger the workflow on a pull request event merge - only for the main branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# Workflow will execute CMake to build x64 Release then call Incredibuild to distribute compilation.
jobs:
    build:
      # The type of runner that the job will run on
      runs-on: self-hosted
      defaults:
        run:
           shell: powershell

    # Steps/tasks to execute
      steps:
      - uses: actions/checkout@v2

      - name: cmake x64 release
        #working-directory: C:\thelab\code\github\opencv\out\build\
        run: |
            cd C:\thelab\code\github\ib-opencv-demo\out\build
            write-output ${pwd}
            write-output ${env:PATH}
            #Add-Content $env:GITHUB_PATH "C:\Program Files\Cmake\bin"
            write-output ${env:GITHUB_PATH}
            #echo "C:\Program Files\Cmake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            #cmake -G "Visual Studio 16 2019" -A x64 -S ..\.. -B "x64-Release"
    
    incredibuild:
      # Type of runner job will run on
      runs-on: self-hosted

      # We need the build job completed to compile
      needs: build

      # Steps/tasks to execute
      steps:
      - uses: actions/checkout@v2

      - name: have Incredibuild run and distribute the compilation to the grid
        #working-directory: C:\thelab\code\github\opencv\out\build\x64-Release
        run: |
            cd C:\thelab\code\github\ib-opencv-demo\out\build\x64-Release
            write-output ${pwd}
            #BuildConsole OpenCV.sln /rebuild /cfg="Release|x64"

