# This is a basic workflow that is manually triggered

name: CI-IB trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
# Trigger the workflow on a pull request event merge - only for the main branch
  pull_request:
    types:
      - closed
    branches:
      - 'main/**'

# Workflow will execute CMake to build x64 Release then call Incredibuild to distribute compilation.
jobs:
    build:
      # The type of runner that the job will run on
      runs-on: "self-hosted"

    # Steps/tasks to execute
      steps:

      - name: enter build directory
        run: cd C:\thelab\code\github\opencv\out\build\ 

      - name: cmake x64 release
        uses: actions/checkout@v2
        run: cmake -G "Visual Studio 16 2019" -A x64 -S ..\.. -B "x64-Release"
    
    incredibuild:
      # Type of runner job will run on
      runs-on: self-hosted

      # We need the build job to completed to compile
      needs: build

      # Steps/tasks to execute
      steps:
      - name: enter the x64-Release directory
        run: cd C:\thelab\code\github\opencv\out\build\x64-Release

      - name: have Incredibuild run and distribute the compilation to the grid
        uses: actions/checkout@v2
        run: BuildConsole OpenCV.sln /rebuild /cfg="Release|x64"

