# This is a basic workflow that is manually triggered

name: CI-IB trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

# Trigger the workflow on a pull request event merge - only for the main branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main

# Workflow will execute CMake to build x64 Release then call Incredibuild to distribute compilation.
jobs:
    
    incredibuild:
      # Type of runner job will run on
      runs-on: [self-hosted, Windows, X64, cloud-ib-demo]
      defaults:
        run:
           shell: cmd

      # Steps/tasks to execute
      steps:
      - uses: actions/checkout@v2

      - name: Have Incredibuild run and distribute the compilation to the grid
        run: |
            cd C:\thelab\code\github\ib-opencv-demo\out\build\x64-Debug-Ninja
            echo "Setting up environment..."
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
            echo "Updated Path"
            echo "Here we go...3"
            echo "Executing Incredibuild..."
            buildconsole /command="cmake --build . --clean-first -j 200"            
